import { randomUUID } from 'crypto';
import type { PrismaClient, Salon } from '@prisma/client';
import { encodeSalonQr, parseSalonQr } from '@salon/shared';
import { RegistrationError } from './registration-error';

/**
 * SalonRegistration handles salon creation with QR token generation,
 * QR payload retrieval, and QR-based salon resolution.
 *
 * - createSalon: generates a unique qr_token on creation (R7.1)
 * - getSalonQrPayload: encodes the salon's qr_token into a QR payload
 * - resolveSalonByQr: resolves a QR payload to a salon, distinguishing
 *   malformed (R7.5) from unregistered (R7.4)
 */
export class SalonRegistration {
  private readonly prisma: PrismaClient;
  /**
   * Optional deep-link base (`<publicBaseUrl>/s/`) for QR encode/parse. When
   * undefined the shared codec default (`https://book.salon.app/s/`) is used.
   * Kept in sync with {@link QrService} so payloads encode and resolve against
   * the same base (e.g. a LAN IP origin in dev).
   */
  private readonly qrDeepLinkBase?: string;

  constructor(prisma: PrismaClient, options: { publicBaseUrl?: string } = {}) {
    this.prisma = prisma;
    this.qrDeepLinkBase = options.publicBaseUrl
      ? `${options.publicBaseUrl.replace(/\/+$/, '')}/s/`
      : undefined;
  }

  /**
   * Create a new salon with a unique qr_token.
   *
   * The qr_token is generated via crypto.randomUUID (R7.1).
   */
  async createSalon(name: string, timezone?: string): Promise<Salon> {
    const qrToken = randomUUID();

    const salon = await this.prisma.salon.create({
      data: {
        name,
        qrToken,
        ...(timezone ? { timezone } : {}),
      },
    });

    return salon;
  }

  /**
   * Get the encoded QR payload for a salon.
   *
   * Returns the deep link string generated by encodeSalonQr from the shared package.
   * Throws if the salon does not exist.
   */
  async getSalonQrPayload(salonId: string): Promise<string> {
    const salon = await this.prisma.salon.findUnique({
      where: { id: salonId },
    });

    if (!salon) {
      throw new Error(`Salon not found: ${salonId}`);
    }

    return encodeSalonQr(salon.qrToken, this.qrDeepLinkBase);
  }

  /**
   * Resolve a scanned QR payload to a salon.
   *
   * 1. Parse the payload using parseSalonQr from the shared package.
   * 2. If malformed → throw RegistrationError with code QR_MALFORMED (R7.5).
   * 3. If ok → query the salon by qr_token.
   * 4. If not found → throw RegistrationError with code QR_UNREGISTERED (R7.4).
   * 5. If found → return the salon (R7.2).
   */
  async resolveSalonByQr(qrPayload: string): Promise<Salon> {
    const parseResult = parseSalonQr(qrPayload, this.qrDeepLinkBase);

    if (parseResult.kind === 'malformed') {
      throw new RegistrationError('QR_MALFORMED');
    }

    const salon = await this.prisma.salon.findUnique({
      where: { qrToken: parseResult.salonToken },
    });

    if (!salon) {
      throw new RegistrationError('QR_UNREGISTERED');
    }

    return salon;
  }
}
