import { controllerRouteDto, controllerPathParams, type ControllerDtoDefinition } from '../../common/dto/index.js';
import { AnyQueryDto, EmptyDto } from '../../common/dto/index.js';
import {
  PlatformAdminAppointmentActionDto,
  PlatformAdminCreateDto,
  PlatformAdminUpdateDto,
  PlatformAppointmentCreateDto,
  PlatformAppointmentUpdateDto,
  PlatformCustomerCreateDto,
  PlatformCustomerUpdateDto,
  PlatformAdminDetailParamDto,
  PlatformAdminIdDto,
  PlatformAdminQueryDto,
  PlatformSalonCreateDto,
  PlatformSalonResourceCreateDto,
  PlatformSalonResourceUpdateDto,
  PlatformSalonUpdateDto,
  PlatformServiceCreateDto,
  PlatformServiceUpdateDto,
  PlatformStaffCreateDto,
  PlatformStaffUpdateDto,
  PlatformSubscriptionUpdateDto,
  PlatformWaitlistUpdateDto,
  PlatformPaymentUpdateDto,
  PlatformAdminStatusDto,
  PlatformCardOrderUpdateDto,
  PlatformSupportTicketUpdateDto,
} from './platform-admin.dto.js';

const route = controllerRouteDto.bind(null, 'PlatformAdminController');

export const PLATFORM_ADMIN_CONTROLLER_DTO_DEFINITIONS = [
  route('platform-admin.dashboard.read', 'GET', '/api/platform-admin/dashboard'),
  route('platform-admin.salons.list', 'GET', '/api/platform-admin/salons', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.salons.create', 'POST', '/api/platform-admin/salons', EmptyDto, AnyQueryDto, PlatformSalonCreateDto),
  route('platform-admin.salons.read', 'GET', '/api/platform-admin/salons/:id', PlatformAdminIdDto),
  route('platform-admin.salons.update', 'PATCH', '/api/platform-admin/salons/:id', PlatformAdminIdDto, AnyQueryDto, PlatformSalonUpdateDto),
  route('platform-admin.salons.delete', 'DELETE', '/api/platform-admin/salons/:id', PlatformAdminIdDto),
  route('platform-admin.details.read', 'GET', '/api/platform-admin/details/:resource/:id', PlatformAdminDetailParamDto),
  route('platform-admin.salons.status', 'PATCH', '/api/platform-admin/salons/:id/status', PlatformAdminIdDto, AnyQueryDto, PlatformAdminStatusDto),
  route('platform-admin.customers.list', 'GET', '/api/platform-admin/customers', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.customers.create', 'POST', '/api/platform-admin/customers', EmptyDto, AnyQueryDto, PlatformCustomerCreateDto),
  route('platform-admin.customers.update', 'PATCH', '/api/platform-admin/customers/:id', PlatformAdminIdDto, AnyQueryDto, PlatformCustomerUpdateDto),
  route('platform-admin.customers.status', 'PATCH', '/api/platform-admin/customers/:id/status', PlatformAdminIdDto, AnyQueryDto, PlatformAdminStatusDto),
  route('platform-admin.customers.delete', 'DELETE', '/api/platform-admin/customers/:id', PlatformAdminIdDto),
  route('platform-admin.staff.list', 'GET', '/api/platform-admin/staff', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.staff.create', 'POST', '/api/platform-admin/staff', EmptyDto, AnyQueryDto, PlatformStaffCreateDto),
  route('platform-admin.staff.update', 'PATCH', '/api/platform-admin/staff/:id', PlatformAdminIdDto, AnyQueryDto, PlatformStaffUpdateDto),
  route('platform-admin.staff.delete', 'DELETE', '/api/platform-admin/staff/:id', PlatformAdminIdDto),
  route('platform-admin.staff.status', 'PATCH', '/api/platform-admin/staff/:id/status', PlatformAdminIdDto, AnyQueryDto, PlatformAdminStatusDto),
  route('platform-admin.platform-admins.list', 'GET', '/api/platform-admin/platform-admins', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.platform-admins.create', 'POST', '/api/platform-admin/platform-admins', EmptyDto, AnyQueryDto, PlatformAdminCreateDto),
  route('platform-admin.platform-admins.update', 'PATCH', '/api/platform-admin/platform-admins/:id', PlatformAdminIdDto, AnyQueryDto, PlatformAdminUpdateDto),
  route('platform-admin.platform-admins.delete', 'DELETE', '/api/platform-admin/platform-admins/:id', PlatformAdminIdDto),
  route('platform-admin.services.list', 'GET', '/api/platform-admin/services', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.services.create', 'POST', '/api/platform-admin/services', EmptyDto, AnyQueryDto, PlatformServiceCreateDto),
  route('platform-admin.services.update', 'PATCH', '/api/platform-admin/services/:id', PlatformAdminIdDto, AnyQueryDto, PlatformServiceUpdateDto),
  route('platform-admin.services.delete', 'DELETE', '/api/platform-admin/services/:id', PlatformAdminIdDto),
  route('platform-admin.chairs.list', 'GET', '/api/platform-admin/chairs', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.chairs.create', 'POST', '/api/platform-admin/chairs', EmptyDto, AnyQueryDto, PlatformSalonResourceCreateDto),
  route('platform-admin.chairs.update', 'PATCH', '/api/platform-admin/chairs/:id', PlatformAdminIdDto, AnyQueryDto, PlatformSalonResourceUpdateDto),
  route('platform-admin.chairs.delete', 'DELETE', '/api/platform-admin/chairs/:id', PlatformAdminIdDto),
  route('platform-admin.equipment.list', 'GET', '/api/platform-admin/equipment', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.equipment.create', 'POST', '/api/platform-admin/equipment', EmptyDto, AnyQueryDto, PlatformSalonResourceCreateDto),
  route('platform-admin.equipment.update', 'PATCH', '/api/platform-admin/equipment/:id', PlatformAdminIdDto, AnyQueryDto, PlatformSalonResourceUpdateDto),
  route('platform-admin.equipment.delete', 'DELETE', '/api/platform-admin/equipment/:id', PlatformAdminIdDto),
  route('platform-admin.appointments.list', 'GET', '/api/platform-admin/appointments', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.appointments.create', 'POST', '/api/platform-admin/appointments', EmptyDto, AnyQueryDto, PlatformAppointmentCreateDto),
  route('platform-admin.appointments.update', 'PATCH', '/api/platform-admin/appointments/:id', PlatformAdminIdDto, AnyQueryDto, PlatformAppointmentUpdateDto),
  route('platform-admin.appointments.delete', 'DELETE', '/api/platform-admin/appointments/:id', PlatformAdminIdDto),
  route('platform-admin.appointments.action', 'POST', '/api/platform-admin/appointments/:id/action', PlatformAdminIdDto, AnyQueryDto, PlatformAdminAppointmentActionDto),
  route('platform-admin.subscriptions.list', 'GET', '/api/platform-admin/subscriptions', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.subscriptions.update', 'PATCH', '/api/platform-admin/subscriptions/:id', PlatformAdminIdDto, AnyQueryDto, PlatformSubscriptionUpdateDto),
  route('platform-admin.subscriptions.delete', 'DELETE', '/api/platform-admin/subscriptions/:id', PlatformAdminIdDto),
  route('platform-admin.payments.list', 'GET', '/api/platform-admin/payments', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.payments.update', 'PATCH', '/api/platform-admin/payments/:id', PlatformAdminIdDto, AnyQueryDto, PlatformPaymentUpdateDto),
  route('platform-admin.waitlist.list', 'GET', '/api/platform-admin/waitlist', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.waitlist.update', 'PATCH', '/api/platform-admin/waitlist/:id', PlatformAdminIdDto, AnyQueryDto, PlatformWaitlistUpdateDto),
  route('platform-admin.waitlist.delete', 'DELETE', '/api/platform-admin/waitlist/:id', PlatformAdminIdDto),
  route('platform-admin.qr-scans.list', 'GET', '/api/platform-admin/qr-scans', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.audit-logs.list', 'GET', '/api/platform-admin/audit-logs', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.card-orders.list', 'GET', '/api/platform-admin/card-orders', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.card-orders.update', 'PATCH', '/api/platform-admin/card-orders/:id', PlatformAdminIdDto, AnyQueryDto, PlatformCardOrderUpdateDto),
  route('platform-admin.support.list', 'GET', '/api/platform-admin/support/tickets', EmptyDto, PlatformAdminQueryDto),
  route('platform-admin.support.read', 'GET', '/api/platform-admin/support/tickets/:id', PlatformAdminIdDto),
  route('platform-admin.support.update', 'PATCH', '/api/platform-admin/support/tickets/:id', PlatformAdminIdDto, AnyQueryDto, PlatformSupportTicketUpdateDto),
] as const satisfies readonly ControllerDtoDefinition[];
