import {
  controllerPathParams,
  controllerRouteDto,
  type ControllerDtoDefinition,
} from '../../common/dto/index.js';
import {
  AdminApprovalPolicyDto,
  AdminAvailabilityBlockDto,
  AdminBookingPolicyDto,
  AdminBrandAccentDto,
  AdminChairDto,
  AdminChairPatchDto,
  AdminClientDto,
  AdminClientQueryDto,
  AdminCalendarQueryDto,
  AdminEmergencyCloseDto,
  AdminHolidayDto,
  AdminMessageDto,
  AdminNoteDto,
  AdminOwnApprovalDto,
  AdminServiceDto,
  AdminServicePatchDto,
  AdminServiceStaffDto,
  AdminSmsSettingsDto,
  AdminStaffDto,
  AdminStaffPatchDto,
  AdminWaitlistQueryDto,
  AdminWorkingHoursDto,
} from './admin.dto.js';
import { AppointmentIdDto, ManagedRescheduleDto } from '../../appointment/dto/index.js';
import { AnyQueryDto, EmptyDto, IdParamDto } from '../../common/dto/index.js';

const route = controllerRouteDto.bind(null, 'AdminController');

export const ADMIN_CONTROLLER_DTO_DEFINITIONS = [
  route('admin.calendar.read', 'GET', '/api/salons/:id/calendar', IdParamDto, AdminCalendarQueryDto),
  route('admin.waitlist.read', 'GET', '/api/salons/:id/waitlist', IdParamDto, AdminWaitlistQueryDto),
  route('admin.customer.read', 'GET', '/api/salons/:id/customers/:customerId', controllerPathParams('id', 'customerId')),
  route('admin.appointment.reschedule-managed', 'POST', '/api/appointments/:id/reschedule-managed', AppointmentIdDto, AnyQueryDto, ManagedRescheduleDto),
  route('admin.appointment.customer.read', 'GET', '/api/appointments/:id/customer', AppointmentIdDto),
  route('admin.appointment.customer-notes', 'POST', '/api/appointments/:id/customer-notes', AppointmentIdDto, AnyQueryDto, AdminNoteDto),
  route('admin.appointment.message', 'POST', '/api/appointments/:id/message', AppointmentIdDto, AnyQueryDto, AdminMessageDto),
  route('admin.pending.read', 'GET', '/api/salons/:id/pending', IdParamDto),
  route('admin.analytics.read', 'GET', '/api/salons/:id/analytics', IdParamDto, AdminCalendarQueryDto),
  route('admin.staff.list', 'GET', '/api/salons/:id/staff', IdParamDto),
  route('admin.clients.list', 'GET', '/api/salons/:id/clients', IdParamDto, AdminClientQueryDto),
  route('admin.clients.create', 'POST', '/api/salons/:id/clients', IdParamDto, AnyQueryDto, AdminClientDto),
  route('admin.sms-settings.read', 'GET', '/api/salons/:id/sms-settings', IdParamDto),
  route('admin.sms-settings.update', 'PATCH', '/api/salons/:id/sms-settings', IdParamDto, AnyQueryDto, AdminSmsSettingsDto),
  route('admin.staff.create', 'POST', '/api/salons/:id/staff', IdParamDto, AnyQueryDto, AdminStaffDto),
  route('admin.staff.update', 'PATCH', '/api/staff/:id', IdParamDto, AnyQueryDto, AdminStaffPatchDto),
  route('admin.chairs.list', 'GET', '/api/salons/:id/chairs', IdParamDto),
  route('admin.working-hours.read', 'GET', '/api/salons/:id/working-hours', IdParamDto),
  route('admin.working-hours.update', 'PUT', '/api/salons/:id/working-hours', IdParamDto, AnyQueryDto, AdminWorkingHoursDto),
  route('admin.booking-policy.read', 'GET', '/api/salons/:id/booking-policy', IdParamDto),
  route('admin.booking-policy.update', 'PUT', '/api/salons/:id/booking-policy', IdParamDto, AnyQueryDto, AdminBookingPolicyDto),
  route('admin.staff-working-hours.read', 'GET', '/api/salons/:id/staff/:staffId/working-hours', controllerPathParams('id', 'staffId')),
  route('admin.staff-working-hours.update', 'PUT', '/api/salons/:id/staff/:staffId/working-hours', controllerPathParams('id', 'staffId'), AnyQueryDto, AdminWorkingHoursDto),
  route('admin.chairs.create', 'POST', '/api/salons/:id/chairs', IdParamDto, AnyQueryDto, AdminChairDto),
  route('admin.chairs.update', 'PATCH', '/api/salons/:id/chairs/:chairId', controllerPathParams('id', 'chairId'), AnyQueryDto, AdminChairPatchDto),
  route('admin.chairs.delete', 'DELETE', '/api/salons/:id/chairs/:chairId', controllerPathParams('id', 'chairId')),
  route('admin.services.create', 'POST', '/api/salons/:id/services', IdParamDto, AnyQueryDto, AdminServiceDto),
  route('admin.services.update', 'PATCH', '/api/salons/:id/services/:serviceId', controllerPathParams('id', 'serviceId'), AnyQueryDto, AdminServicePatchDto),
  route('admin.services.staff.update', 'PUT', '/api/salons/:id/services/:serviceId/staff', controllerPathParams('id', 'serviceId'), AnyQueryDto, AdminServiceStaffDto),
  route('admin.services.delete', 'DELETE', '/api/salons/:id/services/:serviceId', controllerPathParams('id', 'serviceId')),
  route('admin.approval-policy.read', 'GET', '/api/salons/:id/approval-policy', IdParamDto),
  route('admin.auto-approve.salon', 'POST', '/api/salons/:id/auto-approve', IdParamDto, AnyQueryDto, AdminApprovalPolicyDto),
  route('admin.auto-approve.staff', 'POST', '/api/staff/:id/auto-approve', IdParamDto, AnyQueryDto, AdminOwnApprovalDto),
  route('admin.approve-own.staff', 'POST', '/api/staff/:id/approve-own', IdParamDto, AnyQueryDto, AdminOwnApprovalDto),
  route('admin.brand-accent.update', 'POST', '/api/salons/:id/brand-accent', IdParamDto, AnyQueryDto, AdminBrandAccentDto),
  route('admin.holidays.list', 'GET', '/api/salons/:id/holidays', IdParamDto),
  route('admin.holidays.create', 'POST', '/api/salons/:id/holidays', IdParamDto, AnyQueryDto, AdminHolidayDto),
  route('admin.holidays.delete', 'DELETE', '/api/salons/:id/holidays/:holidayId', controllerPathParams('id', 'holidayId')),
  route('admin.emergency-close', 'POST', '/api/salons/:id/emergency-close', IdParamDto, AnyQueryDto, AdminEmergencyCloseDto),
  route('admin.availability-blocks.list', 'GET', '/api/staff/:staffId/availability-blocks', controllerPathParams('staffId')),
  route('admin.availability-blocks.create', 'POST', '/api/staff/:staffId/availability-blocks', controllerPathParams('staffId'), AnyQueryDto, AdminAvailabilityBlockDto),
  route('admin.availability-blocks.delete', 'DELETE', '/api/staff/:staffId/availability-blocks/:blockId', controllerPathParams('staffId', 'blockId')),
  route('admin.manage-availability.staff', 'POST', '/api/staff/:id/manage-availability', IdParamDto, AnyQueryDto, AdminOwnApprovalDto),
] as const satisfies readonly ControllerDtoDefinition[];
