/**
 * Provider port for OTP delivery.
 *
 * The optional code lets providers such as Melli Payamak shared templates
 * receive the code generated by AuthService. Provider-generated OTP services
 * may ignore it and return their own code instead.
 */
export interface OtpProvider {
  sendOtp(phone: string, code?: string): Promise<OtpDeliveryResult>;
}

export type OtpDeliveryResult =
  | { ok: true; providerId: string; code: string }
  | { ok: false; error: string };
